export const bookData = [
  {
    id: 1,
    title: "The Monk Sold His Ferrari",
    author: "Robin Sharma",
    category: "Personal Development",
    to: "personal-development",
    src: "https://res.cloudinary.com/dtinnnjnt/image/upload/v1670662682/lms/books/the_freedom_manifesto_zyyz46.jpg",
  },
  {
    id: 2,
    title: "The 5AM Club",
    author: "Robin Sharma",
    category: "Business and Economics",
    to: "business-and-economics",
    src: "https://res.cloudinary.com/dtinnnjnt/image/upload/v1670662682/lms/books/the_freedom_manifesto_zyyz46.jpg",
  },
  {
    id: 3,
    title: "Do Epic Shit",
    author: "Ankur Warikoo",
    category: "Personal Development",
    to: "personal-development",
    src: "https://res.cloudinary.com/dtinnnjnt/image/upload/v1670662682/lms/books/the_freedom_manifesto_zyyz46.jpg",
  },
  {
    id: 4,
    title: "The Alchemist",
    author: "Paulo Coelho",
    category: "Fiction",
    to: "fiction",
    src: "https://res.cloudinary.com/dtinnnjnt/image/upload/v1670662682/lms/books/the_freedom_manifesto_zyyz46.jpg",
  },
  {
    id: 5,
    title: "Harry Potter and the Philosopher's Stone",
    author: "J.K. Rowling",
    category: "Action and Adventure",
    to: "action-and-adventure",
    src: "https://res.cloudinary.com/dtinnnjnt/image/upload/v1670662682/lms/books/the_freedom_manifesto_zyyz46.jpg",
  },
  {
    id: 6,
    title: "The Power of Your Subconscious Mind",
    author: "Joseph Murphy",
    category: "Religion and Sprituality",
    to: "religion-and-sprituality",
    src: "https://res.cloudinary.com/dtinnnjnt/image/upload/v1670662682/lms/books/the_freedom_manifesto_zyyz46.jpg",
  },
  {
    id: 7,
    title: "The Monk Who Sold His Ferrari",
    author: "Robin Sharma",
    category: "Religion and Sprituality",
    to: "religion-and-sprituality",
    src: "https://res.cloudinary.com/dtinnnjnt/image/upload/v1670662682/lms/books/the_freedom_manifesto_zyyz46.jpg",
  },
  {
    id: 8,
    title: "Atomic Habits",
    author: "James Clear",
    category: "Personal Development",
    to: "personal-development",
    src: "https://res.cloudinary.com/dtinnnjnt/image/upload/v1670662682/lms/books/the_freedom_manifesto_zyyz46.jpg",
  },
  {
    id: 9,
    title: "Becoming",
    author: "Michelle Obama",
    category: "Biographies",
    to: "biographies",
    src: "https://res.cloudinary.com/dtinnnjnt/image/upload/v1670662682/lms/books/the_freedom_manifesto_zyyz46.jpg",
  },
  {
    id: 10,
    title: "The Psychology of Money",
    author: "Morgan Housel",
    category: "Business and Economics",
    to: "business-and-economics",
    src: "https://res.cloudinary.com/dtinnnjnt/image/upload/v1670662682/lms/books/the_freedom_manifesto_zyyz46.jpg",
  },
  {
    id: 11,
    title: "Rich Dad Poor Dad",
    author: "Robert T. Kiyosaki ",
    category: "Business and Economics",
    to: "business-and-economics",
    src: "https://res.cloudinary.com/dtinnnjnt/image/upload/v1670662682/lms/books/the_freedom_manifesto_zyyz46.jpg",
  },
  {
    id: 12,
    title: "Sapiens: A Brief History of Humankind",
    author: "Yuval Noah Harari",
    category: "History",
    to: "history",
    src: "https://res.cloudinary.com/dtinnnjnt/image/upload/v1670662682/lms/books/the_freedom_manifesto_zyyz46.jpg",
  },
  {
    id: 13,
    title: "Get Epic Shit Done",
    author: "Ankur Warikoo",
    category: "Personal Development",
    to: "personal-development",
    src: "https://res.cloudinary.com/dtinnnjnt/image/upload/v1670662682/lms/books/the_freedom_manifesto_zyyz46.jpg",
  },
  {
    id: 14,
    title: "The Freedom Manifesto",
    author: "Karan Bajaj",
    category: "Personal Development",
    to: "personal-development",
    src: "https://res.cloudinary.com/dtinnnjnt/image/upload/v1670662682/lms/books/the_freedom_manifesto_zyyz46.jpg",
  },
  {
    id: 15,
    title: "The Seeker",
    author: "Karan Bajaj",
    category: "Religion and Sprituality",
    to: "religion-and-sprituality",
    src: "https://res.cloudinary.com/dtinnnjnt/image/upload/v1670662682/lms/books/the_freedom_manifesto_zyyz46.jpg",
  },
]
