export const bookData = [
  {
    id: 1,
    title: "It Starts With Us",
    author: "Colleen Hoover",
    category: "Fiction",
    to: "fiction",
    date: "2022-10-18",
    src: "https://res.cloudinary.com/dtinnnjnt/image/upload/v1670772292/lms/books/it-starts-with-us_q3eiqo.webp",
  },
  {
    id: 2,
    title: "The 5AM Club",
    author: "Robin Sharma",
    category: "Business and Economics",
    to: "business-and-economics",
    date: "2022-10-12",
    src: "https://res.cloudinary.com/dtinnnjnt/image/upload/v1670772292/lms/books/the-5-am-club_lcih4t.webp",
  },
  {
    id: 3,
    title: "Do Epic Shit",
    author: "Ankur Warikoo",
    category: "Personal Development",
    to: "personal-development",
    date: "2022-10-12",
    src: "https://res.cloudinary.com/dtinnnjnt/image/upload/v1670771744/lms/books/do-epic-shit_xreqwc.webp",
  },
  {
    id: 4,
    title: "The Alchemist",
    author: "Paulo Coelho",
    category: "Fiction",
    to: "fiction",
    date: "2022-09-12",
    src: "https://res.cloudinary.com/dtinnnjnt/image/upload/v1670772292/lms/books/the-alchemist_pnubzg.webp",
  },
  {
    id: 5,
    title: "Harry Potter and the Philosopher's Stone",
    author: "J.K. Rowling",
    category: "Action and Adventure",
    to: "action-and-adventure",
    date: "2022-09-12",
    src: "https://res.cloudinary.com/dtinnnjnt/image/upload/v1670772617/lms/books/harry-potter-and-the-philosopher-s-stone_tvis4v.webp",
  },
  {
    id: 6,
    title: "The Power of Your Subconscious Mind",
    author: "Joseph Murphy",
    category: "Religion and Sprituality",
    to: "religion-and-sprituality",
    date: "2022-08-12",
    src: "https://res.cloudinary.com/dtinnnjnt/image/upload/v1670772616/lms/books/the-power-of-your-subconscious-mind_yjtn4m.webp",
  },
  {
    id: 7,
    title: "The Monk Who Sold His Ferrari",
    author: "Robin Sharma",
    category: "Religion and Sprituality",
    to: "religion-and-sprituality",
    date: "2022-08-12",
    src: "https://res.cloudinary.com/dtinnnjnt/image/upload/v1670772617/lms/books/the-monk-who-sold-his-ferrari_xgk2ly.webp",
  },
  {
    id: 8,
    title: "Atomic Habits",
    author: "James Clear",
    category: "Personal Development",
    to: "personal-development",
    date: "2022-07-12",
    src: "https://res.cloudinary.com/dtinnnjnt/image/upload/v1670772616/lms/books/atomic-habits_sg87kh.webp",
  },
  {
    id: 9,
    title: "Becoming",
    author: "Michelle Obama",
    category: "Biographies",
    to: "biographies",
    date: "2022-07-12",
    src: "https://res.cloudinary.com/dtinnnjnt/image/upload/v1670772770/lms/books/becoming_grshvz.webp",
  },
  {
    id: 10,
    title: "The Psychology of Money",
    author: "Morgan Housel",
    category: "Business and Economics",
    to: "business-and-economics",
    date: "2022-06-12",
    src: "https://res.cloudinary.com/dtinnnjnt/image/upload/v1670775269/lms/books/the-psychology-of-money_ykn9fq.webp",
  },
  {
    id: 11,
    title: "Rich Dad Poor Dad",
    author: "Robert T. Kiyosaki ",
    category: "Business and Economics",
    to: "business-and-economics",
    date: "2022-06-12",
    src: "https://res.cloudinary.com/dtinnnjnt/image/upload/v1670775103/lms/books/rich-dad-poor-dad_kvbuj1.webp",
  },
  {
    id: 12,
    title: "Sapiens: A Brief History of Humankind",
    author: "Yuval Noah Harari",
    category: "History",
    to: "history",
    date: "2022-05-12",
    src: "https://res.cloudinary.com/dtinnnjnt/image/upload/v1670775103/lms/books/sapiens-a-brief-history-of-humankind_esikei.webp",
  },
  {
    id: 13,
    title: "Get Epic Shit Done",
    author: "Ankur Warikoo",
    category: "Personal Development",
    to: "personal-development",
    date: "2022-12-12",
    src: "https://res.cloudinary.com/dtinnnjnt/image/upload/v1670775103/lms/books/get-epic-shit-done_feqlxl.webp",
  },
  {
    id: 14,
    title: "The Freedom Manifesto",
    author: "Karan Bajaj",
    category: "Personal Development",
    to: "personal-development",
    date: "2022-04-12",
    src: "https://res.cloudinary.com/dtinnnjnt/image/upload/v1670662682/lms/books/the_freedom_manifesto_zyyz46.jpg",
  },
  {
    id: 15,
    title: "The Seeker",
    author: "Karan Bajaj",
    category: "Religion and Sprituality",
    to: "religion-and-sprituality",
    date: "2022-03-12",
    src: "https://res.cloudinary.com/dtinnnjnt/image/upload/v1670775103/lms/books/the-seeker_tyemsg.webp",
  },
]
